sudo: false
language: node_js
services: mongodb
node_js:
  - 7
  - 6
  - 4
addons:
  code_climate:
    repo_token: 0fc59b200a73fa77ebdb522da5a93cf50f11f50378dc1bddeea3e2a38b5f9f4e
script: npm run coverage
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
